### ISSUE TITLE
Render issues for header and separator

### ISSUE THREAD

**Issue by iJackUA** [cebe/markdown#27]
Hi, I have found couple render issues when some tags are not displayed.
Not sure maybe it is wrong Markdown markup, but other parser (I test Ciconia, php-markdown, parsedown and your one) display it as expected 

Example 1
![selection_079](https://f.cloud.github.com/assets/568566/2193909/681f9130-9884-11e3-9bb3-83711ded9bf9.png)

```
# hello, This is Markdown Live Preview

----
## what is Markdown?
see [Wikipedia](http://en.wikipedia.org/wiki/Markdown)

{mycustom_widget}

### Tasks list
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported


* SHA: 16c999e8c71134401a78d4d46435517b2271d6ac
* User@SHA: mojombo@16c999e8c71134401a78d4d46435517b2271d6ac
* User/Repository@SHA: mojombo/github-flavored-markdown@16c999e8c71134401a78d4d46435517b2271d6ac
* #Num: #1
* User#Num: mojombo#1
* User/Repository#Num: mojombo/github-flavored-markdown#1
```

Example 2
![selection_080](https://f.cloud.github.com/assets/568566/2193915/7519ddf0-9884-11e3-823e-2c0ed1a3bd1f.png)

```
----

## changelog 1

* 17-Feb-2013 re-design

----
## changelog 2
* 17-Feb-2013 re-design
```
